[tool.poetry]
name = "manim-mods"
version = "0.1.0"
description = ""
authors = ["Marshall Bruner <brunerm99@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.3"
manim = ">=0.18"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
